language: rust
rust:
    - 1.18.0
    - stable
    - beta
    - nightly
cache: cargo
script:
- cargo test
- cargo test --no-default-features
- cargo test --no-default-features --features std
- cargo test --no-default-features --features backtrace
