language: rust
rust:
    - 1.18.0
    - stable
    - beta
    - nightly
cache: cargo
script:
  - cargo test
  - cargo test --features backtrace
  - cargo test --no-default-features --features "std2 derive"
  - cargo check --no-default-features
  - cargo check --no-default-features --features std2
